chain =input('Please introduce a DNA chain: ')
chain = chain.upper()
length_chain = len(chain)
print('The length of the chain: ',length_chain)
A_count = chain.count('A')
C_count = chain.count('C')
T_count = chain.count('T')
G_count = chain.count('G')
print('A:',A_count,'\nC:',C_count,'\nT:',T_count,'\nG:',G_count)
